name: Unit Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -S tests -B tests/build

      - name: Build
        run: cmake --build tests/build

      - name: Run tests
        run: ./tests/build/host_tests
